#ifndef CONFIG_H
#define CONFIG_H

#define LARGURA_TELA 800
#define ALTURA_TELA 600
#define ALTURA_CHAO (ALTURA_TELA - 100)
#define PONTOS_POR_FASE 300.0
#define FATOR_ACELERACAO 0.30
#define TEMPO_TRANSICAO 5.0

#endif